### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by leetaeh00n** [rookiehb/DisMAE#2]
hello,
I have read your paper very well.
I have a question regarding Appendix A. 
Why is the L_cls update minimized instead of maximized?

**Comment by rookiehb** [comment]
Hi, thanks for your interest in this paper.

Appendix A is about the algorithm for the unsupervised domain generation setup. Here, we freeze the weights of encoders and only update the weights of the domain classifier. We want to show whether the domain classifier can identify domain information captured by the semantic encoders.

**Comment by leetaeh00n** [comment]
On second thought, it seems correct that the encoder and the classifier learn in opposite directions.

Thank you for your response.
